services:
  # Base de Datos PostgreSQL 16
  db:
    image: postgres:16-alpine
    container_name: ecosgrti_db
    restart: always
    environment:
      # Usuario Root (Superusuario para mantenimiento)
      POSTGRES_DB: ecosgrti_db
      POSTGRES_USER: root_admin
      POSTGRES_PASSWORD: root_password
      # Variables personalizadas para nuestro script de inicio
      APP_DB_USER: ecos_user
      APP_DB_PASS: ecos_password_2024
    ports:
      - "5433:5432" # Evita conflicto con tu Postgres local
    networks:
      - ecosgrti_network
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  # Caché y Sesiones Redis 7.2
  redis:
    image: redis:7.2-alpine
    container_name: ecosgrti_redis
    networks:
      - ecosgrti_network
    ports:
      - "6379:6379"

  # Backend Laravel 11
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: ecosgrti_backend
    # TÉCNICA KEEP-ALIVE: Mantiene el contenedor despierto sin ejecutar PHP al inicio
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - ecosgrti_network

  # Frontend Angular 20
  frontend:
      # Comentamos temporalmente el build para usar una imagen limpia directa
      # build:
      #   context: ./frontend
      #   dockerfile: ../docker/frontend.Dockerfile
      image: node:22-alpine
      container_name: ecosgrti_frontend
      volumes:
        - ./frontend:/app
      # 📂 Establecemos el directorio de trabajo dentro del contenedor
      working_dir: /app
      ports:
        - "4200:4200"
      # ⏳ Lo mantenemos despierto en espera
      command: tail -f /dev/null
      stdin_open: true
      tty: true
      networks:
        - ecosgrti_network
      dns:
      - 8.8.8.8
      - 8.8.4.4  

networks:
  ecosgrti_network:
    driver: bridge

volumes:
  postgres_data:
